name: Update
on: 
  workflow_dispatch:
    inputs:
      phase:
          type: choice
          description: Select Phase  
          required: true
          options:
            - 'p'
            - 'd'
            - 'q'
      template:
          type: choice
          description: Select template
          required: true
          options:
            - templates

permissions:
  id-token: write
  contents: read

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/584204556825/locations/global/workloadIdentityPools/k8s-pool/providers/k8s-provider'
          service_account: 'testing-demo@testing-project-397510.iam.gserviceaccount.com'

    - name: Make GET request
      run: |
        response=$(curl -s "https://repo.sj.lithium.com/config/values?phase=qa&key=host")
        echo "$response"  # Optional: Print the response for debugging
        echo "::set-output name=response::$response"  # Set an output variable

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud deployment-manager deployments create cloud-armor-deployment --config=templates/cloud_armor_policy.yml --project=testing-project-397510
